version = 0.1
[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "html-parser-stack-prod"
s3_bucket = "html-parser-stack-source"
s3_prefix = "html-parser-stack-prod"
region = "eu-west-2"
profile = "default"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "html-parser-stack-dev"
s3_bucket = "html-parser-stack-source"
s3_prefix = "html-parser-stack-dev"
region = "eu-west-2"
profile = "default"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
